# -*- coding: utf-8 -*-
"""lvl_2 task 2.1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r8gzmcjMH28vi4jUopFsKwWXjqL9-NNq
"""

from typing_extensions import dataclass_transform
# Задача 2.1. 

# Создайте две функции maximum и minimum,
# которые получают список целых чисел в качестве входных данных 
# и возвращают наибольшее и наименьшее число в этом списке соответственно.
# Например,
# * [4,6,2,1,9,63,-134,566]         -> max = 566, min = -134
# * [-52, 56, 30, 29, -54, 0, -110] -> min = -110, max = 56
# * [42, 54, 65, 87, 0]             -> min = 0, max = 87
# * [5]                             -> min = 5, max = 5
# функции sorted, max и min использовать нельзя!

# def minimum(arr):
#    pass

# def maximum(arr):
#   pass

from random import randint

def create_list():
  n = 20
  arr = []
  for i in range (n):
    arr.append(randint(-100,100))
  return arr

data = create_list()
print(data)

def minimum(arr):
  i = 0
  while i < len(arr) - 1:
    m = i
    j = i + 1
    while j < len(arr):
      if arr[j] < arr[m]:
        m = j
      j += 1
    arr[i],arr[m] = arr[m],arr[i]
    i += 1
  print(f"{arr}, min = {arr [0]}")


def maximum(arr):
  i = 0
  while i < len(arr) - 1:
    m = i
    j = i + 1
    while j < len(arr):
      if arr[j] < arr[m]:
        m = j
      j += 1
    arr[i],arr[m] = arr[m],arr[i]
    i += 1
  print(f"{arr}, max = {arr [- 1]}")

minimum(arr)
maximum(arr)